mapbox/dyno

bin/cli.js
because they are not valid when creating a table:
- LastIncreaseDateTime
- LastDecreaseDateTime
=> omit additional keys on export

lib/dynamoRequest.js
Finally tracked down an error that we were swallowing and was able to fix it. This pull makes dyno wait for the Kinesis response before calling its callback and also returns any Kinesis requests to the caller.
Still looking into what's wrong with the failing test. Locally, I'm getting the same failure on both this branch and the `double-dyno` branch.
/cc @rclark
=> Wait for Kinesis response and emit error if it's enabled.

lib/config.js
- Don't unset region (which is required) if endpoint is set.
- Allows user to pass httpOptions (like agent) to the Kinesis
constructor
=> Pass entire kinesisConfig to Kinesis constructor.

.travis.yml, lib/multi.js, test/test.multi.js
Return the results of `dynamoRequests` so that multi-dyno clients can do things like scan and query with streaming results.
Also looks like travis was broken, still trying to run tests with `tap`
=> Expose streaming interface to dyno.multi

lib/config.js, package.json
This is no longer needed to due to upstream aws-sdk changes.
=> Remove preloading of ec2 metadata credentials

bin/cli.js, lib/types.js, test/index.js, test/test.cli.js
Adds base64-encoding for buffers in the dynamodb records exported via CLI. Heavy refactoring in `cli.js`. + adjusts CLI arguments, for example:
```
dyno scan us-east-1/my-table
dyno tables us-east-1
dyno export us-east-1/my-table | dyno import eu-west-1/my-replica
```
@mick what do you think of doing the parameters like this? It feels a little more intuitive to me.
**Needs**
- cli tests
=> CLI adjustments

lib/dynamoRequest.js, test/test.throughput.js
Dyno's retries on `ProvisionedThroughputExceededException` errors may be too aggressive for some situations. This PR requires you to opt-in to dyno-managed retries.  
- by setting `config.retryAggressively = true` when you configure your dyno instance
- by setting `options.throughputAttempts = X` when you make any individual request
If you set neither of these things, dyno itself will not retry any requests that fail with a throughput exception. _However the aws-sdk will retry_ in these situations up to 10 times over the course of ~30 seconds.
@willwhite @mick is this sufficient, or do you think that we ought to expose an option to entirely disable retries on throughput throttling?
=> Opt-in to dyno-manged throughput retries

lib/dynamoRequest.js
This gives the node.js event loop some breathing room between stream `_read` calls. 
Each call to `_read` [pushes another item into the buffer](https://github.com/mapbox/dyno/blob/c549c2d52b6e4ac090287c346fe28f4a12115373/lib/dynamoRequest.js#L69). Each `push` event _can_ trigger the readable stream itself to make another `_read` call. In the event that this is happening synchronously, there may be no room in the event loop to fire and receive [another DynamoDB request](https://github.com/mapbox/dyno/blob/c549c2d52b6e4ac090287c346fe28f4a12115373/lib/dynamoRequest.js#L71).
If that happens to occur at a time when the stream's `_readableState.buffer` is filled beyond its `highWaterMark`, each `_read` operation will keep `status = false` while `item.length` continues to drop one item at a …
=> Stream _read asyncify

lib/dynamoRequest.js
I think that this clarifies the readable stream code in dynamoRequest.js in a good way. I can confirm that this code avoids the root of the problem that https://github.com/mapbox/dyno/pull/73 bypassed. 
In this refactor the stream cannot `end` until a DynamoDB response has come back without a `LastEvaluatedKey`.
Definitely interested in your thoughts on this @mick.
=> Refactor streaming mode

lib/dynamoRequest.js, test/test.item.js
When streaming a request, adds `dbrequest` events that are fired each time a response is received from DynamoDB. Handler is passed the request parameters and the response object. This is useful if you need to diagnose the rates at which your streaming application is making backend requests.
=> Adds backend request events

lib/dynamoRequest.js
Sets a default highWaterMark of 1000, allows you to scale that back with per-request options. 16834 is the readable-stream's default, and this is too high: something like a scan operation will bomb dynamodb with a bunch of requests at first before the stream api has a chance to start throttling.
1000 seemed like a reasonable max value: with a max item size of 400k in dynamodb, this means the most that would ever get buffered in memory is 400MB of data.
=> Configurable highwatermark, max 1000

lib/config.js, test/index.js, test/test.config.js
Allows caller to pass httpOptions to dyno's [DynamoDB client constructor](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property)
=> Allow configurable httpOptions

bin/cli.js, test/test.cli.js
- Uses batch writes during `dyno import` and `dyno put` calls.
- Manages memory better. Previous incarnation would `queue.defer()` too much work and run the process out of memory.
- Argument to specify a file path to feed into CLI write methods
=> CLI write fixes

CHANGELOG.md, README.md, bin/cli.js, index.js, lib/kinesis.js, lib/types.js, package.json, test/index.js, test/test.cli.js, test/test.convertTypes.js, test/test.item.js, test/test.serialization.js
Adds dependency on part of [dynamodb-doc](https://github.com/awslabs/dynamodb-document-js-sdk), which does two-way, recursive transforms between native JavaScript objects and the DynamoDB wire format.
- Add support for [document types (List and Map)][1], [Boolean][2], and [Null][3]
- Native JavaScript arrays will now transform into lists instead of sets
- Add `dyno.createSet()`, which constructs sets (of number, string, or binary
type) that transform to the DynamoDB wire format correctly.
- Drop support for using a wire-formatted object as input.
[1]:http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModel.DataTypes.Document
[2]:http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModel.DataTypes.Boolean …
=> Add support for document types (List and Map), Boolean, and Null

lib/batch.js, lib/dynamoRequest.js, package.json, test/index.js, test/setup.js, test/test.batch.js
Refs #80 
This adds aggregation of unprocessed items across multiple batch requests that a single `dyno.putItems` or `dyno.deleteItems` request might make. The scenario that is tested:
- you have 25 valid records, then one invalid one, then 10 more valid ones in an array
- you `dyno.putItems`
- dyno completes a successful `batchWriteItems` request for the first 25 items, but the second request fails validation -- this results in no writes.
- your `dyno.putItems` request returns an error, with `err.unprocessed` containing the 11 keys (including your invalid one) that were not written
Similar test scenario for `dyno.deleteItems`. Note that this is only tested for the _case of user error_, where you have handed dyno some invalid records. I don't have a good way to simulate a batch write …
=> Safer batch writes

lib/item.js, test/index.js, test/test.itemsize.js
Adds a function that calculates the number of bytes required to store an item. This is an "estimate" because the documentation is scattered and not terribly quantitative.
Still needs some tests.
=> [wip] Estimate item size

bin/cli.js
Setting these vars made it impossible to use the dyno CLI on an EC2 that authenticates via an associated IAM role.
=> Don't set env vars in cli script

lib/batch.js, test/test.batch.js
Batch requests split your input out into as many individual HTTP requests as needed. This allows you to configure the concurrency with which those requests are made. It defaults to 10 concurrent requests and is overridden via `options.concurrency` when you make the batch request.
cc @mick for 2nd :eyes:
=> Configurable batch concurrency

lib/dynamoRequest.js, lib/query.js, test/test.item.js
- Dyno now uses native format (not wire format) for `metas[*].last` (aka `LastEvaluatedKey`).
- Callers must use native format (not wire format) when passing in `opts.start` (aka `ExclusiveStartKey`).
- Improve robustness of tests slightly because the two changes above didn't cause any tests to fail :grin: 
- Remove dead code that was copying `opts.start` to `params.ExclusiveStartKey`. We are doing this in [dynamoRequest](https://github.com/mapbox/dyno/blob/master/lib/dynamoRequest.js#L83).
=> Native types for LastEvaluatedKey and ExclusiveStartKey.

lib/requests.js, test/requests.test.js
The potential for `UnprocessedItems` in batch responses is tricky, especially if you need to make a set of requests. This branch sketches out consolidating some of the logic in dyno. The idea is:
1. `dyno.batchWriteItemRequests(params)` lets you hand in > 100 items to write. The function returns an array of unsent requests with a `.sendAll()` method attached.
2. The caller can then handle sending the requests themselves, or
3. use `.sendAll([concurrency], callback)` to ask dyno to send the requests. Concurrency defaults to 1. This **always sends all the requests** before firing the callback function, even if one of the requests fails. 
4. The callback function fires with three arguments:
- `err`: **null** if there were no errors, otherwise **an array** of error objects with the same …
=> [wip] Managing batch get/write responses

index.js, lib/serialization.js, package.json, test/index.test.js, test/serialization.test.js
Dyno utilizes a Set shim object provided by the aws-sdk. The shim has a bug (https://github.com/aws/aws-sdk-js/issues/801): when the first entry in the provided list is falsy (i.e. `''` or `0`), the set object has no `.type` property attached. 
When the aws-sdk document client sees this un-typed set in the process of constructing a DynamoDB request, it fails, leading to a request with invalid parameters that fails validation.
This PR is a hotfix right now for a couple of places where dyno encounters this problem explicitly. However it is by no means a complete solution. That'll need to wait for an upstream fix. Leaving this open until that arrives.
=> Sets must always be typed

CHANGELOG.md, bin/cli.js, test/cli.test.js
There was an issue with the CLI parser dropping attributes from the first line of the `export` output which defines the table's properties that should be imported.
Fixes #96
=> Roundtrip cli export --> import

API.md, index.js, lib/requests.js, lib/stream.js, lib/util.js, test/index.test.js, test/requests.test.js
Adds new functions to handle multiple BatchWriteItem or BatchGetItem requests:
- follows the same pattern from `batchGetItemRequests` or `batchWriteItemRequests` where you
```js
dyno.batchWriteAll(params).sendAll(10, callback);
```
- the `sendAll` implementation retries unprocessed items until there are none left.
- the callback from `sendAll` is given a single err object (even if multiple requests errored), and a single response object (or null if all requests errored). If any requests were successful, the response object is an aggregation of all the successful responses.
fixes #116
=> batchGetAll and batchWriteAll to retry unprocessed

lib/requests.js, test/requests.test.js
Handle a condition where `data.Responses` is not defined by `aws-sdk-js`. It's not 100% clear to me what the underlying condition for this to happen is (echoes of https://github.com/mapbox/s3scan/issues/17) -- we'll learn more by catching and handling this case correctly.
cc @rclark
=> Handle bad data responses

package.json
This gets the aws-sdk version semver compatible between dyno and https://github.com/mapbox/cardboard/pull/187. This is desirable since aws-sdk is massive and adds a lot of weight to installs. Without this `npm dedupe` may fail to collapse the dupes.
=> Accept any 2.x aws-sdk version

CHANGELOG.md, lib/util.js, package-lock.json, package.json, test/util.test.js
When using batch operations the stats are not returned correctly.
For example, this request:
```js
batchWriteAll({
RequestItems: { ... },
ReturnConsumedCapacity: 'INDEXES',
ReturnItemCollectionMetrics: 'SIZE'
})
```
causes AWS to return the following data structure:
```js
{
ConsumedCapacity: [{
TableName: 'table',
CapacityUnits: 8,
Table: { CapacityUnits: 4 },
GlobalSecondaryIndexes: { index: { CapacityUnits: 4 } }
}]
}
```
which is then transformed by `reduceCapacity` inside `sendAll` to this:
```js
{
ConsumedCapacity: {
TableName: undefined
}
}
```
This PR fixes that problem.
=> Update reduceCapacity to support new data shape

CHANGELOG.md, index.js, lib/stream.js, lib/util.js, package-lock.json, package.json, test/cli.test.js, test/index.test.js, test/util.test.js
Added a new type of logger that logs structured capacity usage data (ReadCapacityUnits and WriteCapacityUnits) that we can easily use for all our services to get a clear picture of which requests from which service are responsible for our costs.
Detect if the `costLogger` is set in `options`, and if it is:
- Add `ReturnConsumedCapacity: INDEXES` parameter to all executed requests to DynamoDB
- On return from each request, extracted WriteCapacityUnits and ReadCapacityUnits from the response and call the logger function with them. 
- If there is a `dynoInstance` in the option, the `DynamoDBCLient` will be reused
Why don't we use the `logger` option of DynamoDBClient? It is bonded with the instance,  so it is impossible to use different logger for each endpoint while sharing the …
=> Add costLogger

.eslintrc, CHANGELOG.md, index.js, package-lock.json, package.json, test/index.test.js
Added async version of following methods:
- All native methods
- listTablesAsync
- describeTableAsync
- batchGetItemAsync
- batchWriteItemAsync
- deleteItemAsync
- getItemAsync
- putItemAsync
- updateItemAsync
- dynoExtensions
- createTableAsync
- deleteTableAsync
- queryAsync
- scanAsync
=> Add asynchronous versions of existing methods that support callbacks
